# This is prod server only. If you want to develop, you can use the docker-compose.yml file in Docker/dev/docker-compose.yml.

version: "3.9"

volumes:
  pgadmin_data:

services:
  web:
    container_name: matchpoint-web
    image: mateuxlucax/badminton-manager:latest
    restart: unless-stopped
    platform: linux/x86_64
    depends_on:
      - database
    ports:
      - "${APP_PORT}:80"

  scripts:
    container_name: matchpoint-scripts
    build:
      context: ../..
      dockerfile: Docker/server/Dockerfile
    depends_on:
      - database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  database:
    container_name: matchpoint-database
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
      - ../../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    container_name: matchpoint-pgadmin
    image: dpage/pgadmin4:7
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SETUP_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_SETUP_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /servers.json
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/servers.json
      - ./pgpassfile:/pgpassfile
