version: '3.9'

services:
  web:
    build:
      context: ../..
      dockerfile: Docker/dev/Dockerfile
    container_name: badminton-web
    ports:
      - "8080:80"
    volumes:
      - ../../src:/var/www/html/src
      - ../../tests:/var/www/html/tests
      - ../../vendor:/var/www/html/vendor
      - ../../composer.json:/var/www/html/composer.json
      - ../../composer.json:/var/www/html/composer.lock
      - ../../phpunit.xml:/var/www/html/phpunit.xml
      - ../../.env:/var/www/html/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  database:
    image: postgres:15
    container_name: badminton-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - badminton-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  badminton-database:
