version: '3.9'

services:
  web:
    build: .
    container_name: badminton-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/public
      - ./vendor:/var/www/html/vendor
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - XDEBUG_CONFIG=client_port=9003
      - XDEBUG_CONFIG=start_with_request=yes
      - XDEBUG_CONFIG=log=/var/www/html/xdebug.log
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  database:
    image: postgres:15
    container_name: badminton-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - badminton-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  badminton-database:
