name: Build

on:
  workflow_run:
    workflows: [ Tests & Quality Check ]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    needs: tests-and-quality-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Docker/prod/Dockerfile
          push: true
          tags: mateuxlucax/badminton-manager:latest
