name: Tests & Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-and-quality-check:
    name: Tests & Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . -f Docker/prod/Dockerfile -t badminton-manager

      - name: Run tests inside Docker container
        run: docker run -v $(pwd):/app badminton-manager vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
